"""immutable evidence attachments

Revision ID: 51d69315b352
Revises: 8a76265b9880
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "51d69315b352"
down_revision: str | None = "8a76265b9880"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evidence_attachments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("execution_id", sa.Integer(), nullable=True),
        sa.Column("uat_result_id", sa.Integer(), nullable=True),
        sa.Column("filename", sa.String(length=150), nullable=False),
        sa.Column("media_type", sa.String(length=80), nullable=False),
        sa.Column("content", sa.LargeBinary(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("actor", sa.String(length=150), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(execution_id IS NOT NULL AND uat_result_id IS NULL) OR (execution_id IS NULL AND uat_result_id IS NOT NULL)"
        ),
        sa.ForeignKeyConstraint(["execution_id"], ["test_executions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["uat_result_id"], ["uat_results.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("evidence_attachments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_evidence_attachments_execution_id"), ["execution_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_evidence_attachments_uat_result_id"), ["uat_result_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("evidence_attachments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_evidence_attachments_uat_result_id"))
        batch_op.drop_index(batch_op.f("ix_evidence_attachments_execution_id"))

    op.drop_table("evidence_attachments")
    # ### end Alembic commands ###
