"""normalized domain and governed evidence

Revision ID: 73328b7d29ba
Revises:
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "73328b7d29ba"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artifacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("key", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("owner", sa.String(length=150), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["artifacts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    with op.batch_alter_table("artifacts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_artifacts_kind"), ["kind"], unique=False)
        batch_op.create_index(batch_op.f("ix_artifacts_project_id"), ["project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_artifacts_status"), ["status"], unique=False)

    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("actor", sa.String(length=150), nullable=False),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("entity", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("previous_value", sa.JSON(), nullable=True),
        sa.Column("new_value", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_logs_entity_id"), ["entity_id"], unique=False)

    op.create_table(
        "auth_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("csrf_token", sa.String(length=100), nullable=False),
        sa.Column("actor", sa.String(length=150), nullable=False),
        sa.Column("role", sa.String(length=30), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_table(
        "organizations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "simulator_cases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("case_id", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=200), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("role", sa.String(length=30), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "artifact_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("relation", sa.String(length=30), nullable=False),
        sa.CheckConstraint("source_id <> target_id"),
        sa.ForeignKeyConstraint(["source_id"], ["artifacts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_id"], ["artifacts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "target_id", "relation"),
    )
    with op.batch_alter_table("artifact_links", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_artifact_links_source_id"), ["source_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_artifact_links_target_id"), ["target_id"], unique=False)

    op.create_table(
        "changes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("impact", sa.Text(), nullable=False),
        sa.Column("risk", sa.Text(), nullable=False),
        sa.Column("requested_by", sa.String(length=150), nullable=False),
        sa.Column("approved_by", sa.String(length=150), nullable=False),
        sa.Column("analysis_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("analysis_snapshot", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["artifacts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "dependencies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("impact", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["artifacts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["artifacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["artifacts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_type", sa.String(length=80), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["artifacts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "incidents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("environment", sa.String(length=30), nullable=False),
        sa.Column("assigned_to", sa.String(length=150), nullable=False),
        sa.Column("business_impact", sa.Text(), nullable=False),
        sa.Column("technical_impact", sa.Text(), nullable=False),
        sa.Column("root_cause", sa.Text(), nullable=False),
        sa.Column("workaround", sa.Text(), nullable=False),
        sa.Column("resolution", sa.Text(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["id"], ["artifacts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "processes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("current_state", sa.Text(), nullable=False),
        sa.Column("future_state", sa.Text(), nullable=False),
        sa.Column("steps", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["artifacts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["artifacts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "releases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("version", sa.String(length=40), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column("deployment_notes", sa.Text(), nullable=False),
        sa.Column("rollback_plan", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["artifacts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "requirements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=30), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("acceptance_criteria", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["artifacts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "risks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("probability", sa.Integer(), nullable=False),
        sa.Column("impact", sa.Integer(), nullable=False),
        sa.Column("mitigation", sa.Text(), nullable=False),
        sa.CheckConstraint("impact BETWEEN 1 AND 5"),
        sa.CheckConstraint("probability BETWEEN 1 AND 5"),
        sa.ForeignKeyConstraint(["id"], ["artifacts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "stakeholders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=100), nullable=False),
        sa.Column("department", sa.String(length=100), nullable=False),
        sa.Column("contact", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["artifacts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "systems",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("system_type", sa.String(length=60), nullable=False),
        sa.Column("environment", sa.String(length=30), nullable=False),
        sa.Column("criticality", sa.String(length=20), nullable=False),
        sa.Column("technology", sa.String(length=150), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["artifacts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "test_plans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column("objectives", sa.Text(), nullable=False),
        sa.Column("environment", sa.String(length=30), nullable=False),
        sa.Column("entry_criteria", sa.Text(), nullable=False),
        sa.Column("exit_criteria", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["artifacts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "training",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("audience", sa.String(length=150), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["artifacts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "uat_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("coordinator", sa.String(length=150), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(["id"], ["artifacts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "integrations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_system_id", sa.Integer(), nullable=False),
        sa.Column("target_system_id", sa.Integer(), nullable=False),
        sa.Column("protocol", sa.String(length=10), nullable=False),
        sa.Column("direction", sa.String(length=20), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("endpoint", sa.String(length=200), nullable=False),
        sa.Column("method", sa.String(length=30), nullable=False),
        sa.Column("authentication_type", sa.String(length=60), nullable=False),
        sa.Column("data_format", sa.String(length=10), nullable=False),
        sa.Column("request_format", sa.Text(), nullable=False),
        sa.Column("response_format", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["artifacts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["source_system_id"],
            ["systems.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_system_id"],
            ["systems.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "uat_approvals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("stakeholder_id", sa.Integer(), nullable=False),
        sa.Column("actor", sa.String(length=150), nullable=False),
        sa.Column("decision", sa.String(length=20), nullable=False),
        sa.Column("comments", sa.Text(), nullable=False),
        sa.Column("override_reason", sa.Text(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["uat_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stakeholder_id"],
            ["stakeholders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("uat_approvals", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_uat_approvals_session_id"), ["session_id"], unique=False)

    op.create_table(
        "uat_scenarios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("requirement_id", sa.Integer(), nullable=False),
        sa.Column("steps", sa.Text(), nullable=False),
        sa.Column("expected_result", sa.Text(), nullable=False),
        sa.Column("mandatory", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["artifacts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["requirement_id"],
            ["requirements.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["uat_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "field_mappings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("integration_id", sa.Integer(), nullable=False),
        sa.Column("source_field", sa.String(length=80), nullable=False),
        sa.Column("target_field", sa.String(length=80), nullable=False),
        sa.Column("datatype", sa.String(length=20), nullable=False),
        sa.Column("transformation", sa.String(length=20), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("validation_rule", sa.String(length=150), nullable=False),
        sa.ForeignKeyConstraint(["integration_id"], ["integrations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("integration_id", "target_field"),
    )
    with op.batch_alter_table("field_mappings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_field_mappings_integration_id"), ["integration_id"], unique=False
        )

    op.create_table(
        "test_cases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("test_plan_id", sa.Integer(), nullable=False),
        sa.Column("requirement_id", sa.Integer(), nullable=False),
        sa.Column("integration_id", sa.Integer(), nullable=True),
        sa.Column("type", sa.String(length=30), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("preconditions", sa.Text(), nullable=False),
        sa.Column("steps", sa.Text(), nullable=False),
        sa.Column("expected_result", sa.Text(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("expected_status", sa.Integer(), nullable=False),
        sa.Column("scenario", sa.String(length=30), nullable=False),
        sa.Column("mandatory", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["artifacts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["integration_id"],
            ["integrations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requirement_id"],
            ["requirements.id"],
        ),
        sa.ForeignKeyConstraint(
            ["test_plan_id"],
            ["test_plans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "uat_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scenario_id", sa.Integer(), nullable=False),
        sa.Column("actor", sa.String(length=150), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("evidence", sa.Text(), nullable=False),
        sa.Column("comments", sa.Text(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('PASS','FAIL','BLOCKED')"),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["uat_scenarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("uat_results", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_uat_results_scenario_id"), ["scenario_id"], unique=False)

    op.create_table(
        "test_executions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("test_case_id", sa.Integer(), nullable=False),
        sa.Column("environment", sa.String(length=30), nullable=False),
        sa.Column("executed_by", sa.String(length=150), nullable=False),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("actual_result", sa.Text(), nullable=False),
        sa.Column("evidence", sa.Text(), nullable=False),
        sa.Column("request_body", sa.Text(), nullable=False),
        sa.Column("response_body", sa.Text(), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("defect_id", sa.Integer(), nullable=True),
        sa.CheckConstraint("status IN ('PASS','FAIL','BLOCKED','NOT_RUN')", name="ck_test_execution_status"),
        sa.ForeignKeyConstraint(
            ["defect_id"],
            ["incidents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["test_case_id"],
            ["test_cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("test_executions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_test_executions_test_case_id"), ["test_case_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("test_executions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_test_executions_test_case_id"))

    op.drop_table("test_executions")
    with op.batch_alter_table("uat_results", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_uat_results_scenario_id"))

    op.drop_table("uat_results")
    op.drop_table("test_cases")
    with op.batch_alter_table("field_mappings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_field_mappings_integration_id"))

    op.drop_table("field_mappings")
    op.drop_table("uat_scenarios")
    with op.batch_alter_table("uat_approvals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_uat_approvals_session_id"))

    op.drop_table("uat_approvals")
    op.drop_table("integrations")
    op.drop_table("uat_sessions")
    op.drop_table("training")
    op.drop_table("test_plans")
    op.drop_table("systems")
    op.drop_table("stakeholders")
    op.drop_table("risks")
    op.drop_table("requirements")
    op.drop_table("releases")
    op.drop_table("projects")
    op.drop_table("processes")
    op.drop_table("incidents")
    op.drop_table("documents")
    op.drop_table("dependencies")
    op.drop_table("changes")
    with op.batch_alter_table("artifact_links", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_artifact_links_target_id"))
        batch_op.drop_index(batch_op.f("ix_artifact_links_source_id"))

    op.drop_table("artifact_links")
    op.drop_table("users")
    op.drop_table("simulator_cases")
    op.drop_table("organizations")
    op.drop_table("auth_sessions")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_logs_entity_id"))

    op.drop_table("audit_logs")
    with op.batch_alter_table("artifacts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_artifacts_status"))
        batch_op.drop_index(batch_op.f("ix_artifacts_project_id"))
        batch_op.drop_index(batch_op.f("ix_artifacts_kind"))

    op.drop_table("artifacts")
    # ### end Alembic commands ###
