"""bind evidence to contract revisions

Revision ID: 8a76265b9880
Revises: 73328b7d29ba
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "8a76265b9880"
down_revision: str | None = "73328b7d29ba"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("test_executions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("contract_fingerprint", sa.String(length=64), server_default="", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("test_executions", schema=None) as batch_op:
        batch_op.drop_column("contract_fingerprint")

    # ### end Alembic commands ###
